In [1]:
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt

dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [2]:
df_original = df.copy()

df_altered = df_original

df_altered.loc[:5,'salary_year_avg']

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
Name: salary_year_avg, dtype: float64

In [3]:
# calculating the median salary
median_salary = df_altered['salary_year_avg'].median()

# filling missing values with median salary
df_altered['salary_year_avg'] = df_altered.loc[:,'salary_year_avg'].fillna(median_salary)

df_altered['salary_year_avg'] = df_altered['salary_year_avg'].fillna(median_salary)

In [4]:
df_altered.loc[:5,'salary_year_avg']

0    115000.0
1    115000.0
2    115000.0
3    115000.0
4    115000.0
5    115000.0
Name: salary_year_avg, dtype: float64

In [5]:
print('ID of df_original:               ', id(df_original))
print('ID of df_altered:                ', id(df_altered))
print('Are the two dataframes the same? ', id(df_original) == id(df_altered))

ID of df_original:                2338967825360
ID of df_altered:                 2338967825360
Are the two dataframes the same?  True

In [6]:
# Calculating the median salary
median_salary = df_altered['salary_year_avg'].median()

# Filling the missing values with the median salary
df_altered['salary_year_avg'] = df_altered['salary_year_avg'].fillna(median_salary)

df_altered.loc[:5,'salary_year_avg']

0    115000.0
1    115000.0
2    115000.0
3    115000.0
4    115000.0
5    115000.0
Name: salary_year_avg, dtype: float64

In [8]:
df.sample(n=5)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
334722,Data Engineer,Data Engineer III,"Bellevue, WA",via The Muse,Full-time,False,"Florida, United States",2023-05-11 23:17:51,False,True,United States,NaN,NaN,NaN,Chewy,"['sql', 'python', 'ruby', 'ruby', 'java', 'ela...","{'cloud': ['aws', 'redshift'], 'databases': ['..."
79775,Data Engineer,Lead Data Engineer,"Cincinnati, OH",via CareerBuilder,Full-time,False,"Texas, United States",2023-02-20 00:09:17,False,True,United States,NaN,NaN,NaN,Capital One,"['java', 'scala', 'python', 'nosql', 'sql', 'm...","{'cloud': ['redshift', 'snowflake', 'aws', 'az..."
309999,Data Analyst,IT cum Data Analyst,Singapore,via BeBee Singapore,Contractor,False,Singapore,2023-12-28 17:30:59,False,False,Singapore,NaN,NaN,NaN,Lih Ming Construction Pte Ltd,"['sql', 'python', 'r', 'tableau', 'power bi']","{'analyst_tools': ['tableau', 'power bi'], 'pr..."
108610,Data Analyst,Data Analyst,"Lisbon, Portugal",via WhatJobs,Full-time,False,Portugal,2023-01-07 00:29:26,False,False,Portugal,NaN,NaN,NaN,Randstad,['sql'],{'programming': ['sql']}
35131,Data Engineer,Data Engineer,"Bradford, UK",via WANE Jobs,Full-time,False,United Kingdom,2023-07-31 14:00:46,True,False,United Kingdom,NaN,NaN,NaN,Fruition IT Resources Limited,NaN,NaN

In [ ]:
# getting 10% of the actual data (rows in this case)

df.sample(frac=0.1, replace=False)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
206488,Data Scientist,Data Scientist,"Tampa, FL",via BeBee,Full-time,False,"Florida, United States",2023-03-25 22:06:40,False,False,United States,NaN,NaN,NaN,Ascendion Inc.,"['sql', 'aws', 'snowflake', 'power bi']","{'analyst_tools': ['power bi'], 'cloud': ['aws..."
380924,Data Analyst,Head of Data Analytics and Digital Insights,Dubai - United Arab Emirates,via BeBee,Full-time,False,United Arab Emirates,2023-02-06 18:48:12,True,False,United Arab Emirates,NaN,NaN,NaN,Emagine Solutions FZE,NaN,NaN
405566,Senior Data Scientist,Senior Data Scientist,Anywhere,via LinkedIn,Full-time,True,"Texas, United States",2023-11-13 16:04:05,False,False,United States,NaN,NaN,NaN,StormImpact,"['r', 'python', 'sql', 'linux', 'git']","{'os': ['linux'], 'other': ['git'], 'programmi..."
217548,Data Engineer,Data Engineer Wasserkraft (w/m/d),"Vienna, Austria",via XING,Full-time,False,Austria,2023-02-01 23:07:24,True,False,Austria,NaN,NaN,NaN,VERBUND AG,"['sql', 'java', 'python', 'javascript', 'azure...","{'cloud': ['azure'], 'libraries': ['spark'], '..."
509175,Data Analyst,Business Data Analyst,"Alpharetta, GA",via BeBee,Full-time,False,Georgia,2023-09-14 11:31:55,False,True,United States,NaN,NaN,NaN,Aditi Consulting,"['sql', 'python', 'r', 'java', 'sql server', '...","{'analyst_tools': ['tableau', 'looker', 'qlik'..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
426369,Software Engineer,Software Development Engineer in Test for Data,"Minato City, Tokyo, Japan",via BeBee,Full-time,False,Japan,2023-07-22 16:31:50,True,False,Japan,NaN,NaN,NaN,PayPay,"['sql', 'selenium']","{'libraries': ['selenium'], 'programming': ['s..."
415759,Data Scientist,data scientist,"Atlanta, GA",via Trabajo.org,Full-time and Contractor,False,Georgia,2023-10-20 16:49:09,False,True,United States,NaN,NaN,NaN,Randstad,NaN,NaN
182003,Data Scientist,Data Scientist,"Irving, TX",via Jobgigy.com,Full-time,False,Sudan,2023-03-06 16:19:59,False,False,Sudan,NaN,NaN,NaN,Epsilon,"['python', 't-sql', 'azure', 'databricks', 'sp...","{'cloud': ['azure', 'databricks'], 'libraries'..."
654520,Data Scientist,Meteo Data Scientist,"Prague, Czechia",via LinkedIn,Full-time,False,Czechia,2023-04-05 10:31:28,False,False,Czechia,NaN,NaN,NaN,Ezpada Group,"['sql', 'python', 'r', 'matlab', 'matplotlib']","{'libraries': ['matplotlib'], 'programming': [..."
734903,Data Engineer,Azure Data Engineer,"Espoo, Finland",via Trabajo.org,Full-time,False,Finland,2023-08-13 21:28:48,False,False,Finland,NaN,NaN,NaN,Innofactor Finland,"['sql', 't-sql', 'sql server', 'azure', 'datab...","{'cloud': ['azure', 'databricks', 'snowflake']..."